FROM osrf/ros:foxy-desktop

COPY ./crms_demo_robot /root/ros2_ws/src/crms_demo_robot

RUN apt update && apt-get install python3-pip -y

# Install the core packages required to build librealsense libs
#RUN apt install -y git libssl-dev libusb-1.0-0-dev pkg-config libgtk-3-dev
# Install Distribution-specific packages for Ubuntu 18
#RUN apt install -y libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev

RUN pip install pyrealsense2 
RUN pip install requests

WORKDIR /root/ros2_ws
RUN colcon build

ENV ROS_DOMAIN_ID=0
COPY fastrtps-profile.xml /root/fastrtps-profile.xml
ENV FASTRTPS_DEFAULT_PROFILES_FILE=/root/fastrtps-profile.xml
COPY ./ros2_entrypoint.sh /
ENTRYPOINT ["/ros2_entrypoint.sh"]
#CMD ["ros2 run crms_demo_robot FoodListBuilder_node"]
CMD ["ros2", "run", "crms_demo_robot", "Camera_node"]

